In [33]:
import torch

In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [6]:
X=x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

##### 均值为0、标准差为1的标准高斯分布（正态分布）中随机采样

In [9]:
torch.randn(3,4)

tensor([[ 1.7044,  0.4625,  0.4538, -0.0693],
        [ 3.3741, -1.0979, -0.4837, -0.5480],
        [ 0.6892, -0.9399,  0.3765,  2.2990]])

##### 对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。 我们可以在同一形状的任意两个张量上调用按元素操作。 在下面的例子中，我们使用逗号来表示一个具有5个元素的元组，其中每个元素都是按元素操作的结果

In [11]:
# x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,3,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  5.,  6., 10.]),
 tensor([-1., -1.,  2.,  6.]),
 tensor([ 2.,  6.,  8., 16.]),
 tensor([0.5000, 0.6667, 2.0000, 4.0000]),
 tensor([ 1.,  8., 16., 64.]))

In [12]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [14]:
X=torch.arange(12).reshape((3,4))
Y=torch.tensor([[2,1,3,4],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=1)

tensor([[ 0,  1,  2,  3,  2,  1,  3,  4],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [15]:
X==Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
X.sum()

tensor(66)

### 2.1.3. 广播机制
##### 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；对生成的数组执行按元素操作。

In [17]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [18]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4. 索引和切片
##### 与任何Python数组一样：第一个元素的索引是0，最后一个元素索引是-1； 可以指定范围以包含第一个元素和最后一个之前的元素。

如下所示，我们可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素

In [22]:
X,X[-1],X[1:3]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [23]:
X[1,2]=9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [25]:
X[0:2,:] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 2.1.5 节省内存

In [26]:
before=id(Y)
Y=Y+X
id(Y)==before

False

In [28]:
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 2709296710176
id(Z): 2709296710176


###### 如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。

### 2.1.6. 转换为其他Python对象

In [31]:
A = X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [32]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.1.7. 小结

#####  深度学习存储和操作数据的主要接口是张量（维数组）。它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象。