#### 生成数据集 

In [1]:
import numpy as np 
import torch 
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w = torch.tensor([2,-3.4])
true_b = 4.2
features,labels = d2l.synthetic_data(true_w,true_b,1000)

#### 读取数据集 

In [8]:
#is_train:是否希望数据迭代器对象在每个迭代周期内打乱数据。
def load_array(data_arrays,batch_size,is_train=True):
    """构造一个PyTorch数据迭代器"""
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset,batch_size,shuffle=is_train)

batch_size = 10
data_iter = load_array((features,labels),batch_size)

for X,y in data_iter:
    print(X,'\n',y)

tensor([[ 0.1294, -0.6705],
        [ 0.9732, -1.1656],
        [ 0.1104, -1.0397],
        [-0.4357,  0.5962],
        [ 0.2422,  0.1402],
        [-1.8543,  1.7538],
        [ 0.2796,  0.5599],
        [ 0.6759, -0.5576],
        [-0.2690, -0.6499],
        [ 1.3202, -0.4254]]) 
 tensor([[ 6.7580],
        [10.1136],
        [ 7.9636],
        [ 1.3090],
        [ 4.2166],
        [-5.4571],
        [ 2.8613],
        [ 7.4486],
        [ 5.8874],
        [ 8.2767]])
tensor([[ 0.4711, -2.1999],
        [ 0.1259, -0.9905],
        [ 0.7467, -0.6847],
        [ 1.1703, -0.0736],
        [-0.4310, -1.1344],
        [ 0.6216, -0.0630],
        [-0.4615,  0.0243],
        [ 0.5055,  0.8702],
        [ 0.2602,  0.8366],
        [ 1.1331, -0.4958]]) 
 tensor([[12.6244],
        [ 7.8223],
        [ 8.0310],
        [ 6.7841],
        [ 7.1863],
        [ 5.6515],
        [ 3.2052],
        [ 2.2591],
        [ 1.8674],
        [ 8.1444]])
tensor([[-0.1214,  0.7482],
        [ 1.4190, -0.657

#### 使用框架预定义好的层

In [9]:
from torch import nn

net = nn.Sequential(nn.Linear(2,1))

#### 初始化模型参数 

In [15]:
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [19]:
loss = nn.MSELoss()
trainer = torch.optim.SGD(net.parameters(),lr=0.03)


In [20]:
num_epochs = 3
for epoch in range(num_epochs):
    for X,y in data_iter:
        #net（X）自己带了参数
        l = loss(net(X),y)
        #优化器清零
        trainer.zero_grad()
        l.backward()
        #step模型更新
        trainer.step()
    #所有feature
    l = loss(net(features),labels)
    print(f'epoch {epoch+1},loss {l:f}')

epoch 1,loss 0.000106
epoch 2,loss 0.000105
epoch 3,loss 0.000105
