In [13]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [14]:
x.requires_grad_(True)
x.grad

In [15]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [16]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [17]:
x.grad == 4 * x

tensor([True, True, True, True])

In [19]:
#在默认情况下，PyTorch会累计梯度，我们需要清除之前的值。
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [21]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [28]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [29]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [34]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(),requires_grad=True)
d=f(a)
d.backward()

a.grad == d/a

tensor(1.0978, requires_grad=True)